security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false
        main:
            pattern:    ^/
            provider:   fos_userbundle
            form_login:
                csrf_provider:  form.csrf_provider
                login_path:     /connexion
                check_path:     /verifie_login
            logout:     
                path:   /deconnexion
                target: /
            anonymous:  true

    access_control:
        - { path: ^/(connexion|inscription), access: "isAnonymous()" }
