<?php

namespace MyEvents\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AmisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmisRepository extends EntityRepository {

	public function nouvelleDemandeAmi(Utilisateur $oEmetteur, Utilisateur $oDestinataire) {
		$oAmis = new Amis();
		$oAmis->setUtilisateurEmetteur($oEmetteur);
		$oAmis->setUtilisateurDestinataire($oDestinataire);
		$oAmis->setDateReponse(NULL);
		$oAmis->setHistoriqueConversation(NULL);

		$this->_em->persist($oAmis);
		$this->_em->flush();
	}

}
