<?php

namespace MyEvents\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ManifestationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManifestationRepository extends EntityRepository {

}
