<?php

namespace MyEvents\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MarqueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarqueurRepository extends EntityRepository
{
}
