<?php

namespace MyEvents\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeMarqueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeMarqueurRepository extends EntityRepository
{
}
